{
  State.mag
  ExactpAdics.mag
  PrecisionStrategy.mag
  Getter.mag
  UnitTests.mag
  Promotion.mag
  DefaultAssociativeArray.mag
  Val_FldPadElt.mag
  Val_RngUPolElt_FldPad.mag
  MultivariatePolynomials.mag
  Val_RngMPolElt_FldPad.mag
  Roots.mag
  Factorization.mag
}
