site_name: Exact p-Adics
docs_dir: src
extra_css:
  - extra.css
pages:
  - Overview:
    - Introduction: index.md
    - New types: types.md
  - Exact p-Adic Fields:
    - Introduction: fld/intro.md
    - Creation of fields: fld/create.md
    - Basic operations on fields: fld/basics.md
    - Creation of elements: fld/elt-create.md
    - Basic operations on elements: fld/elt-basics.md
    - Residue class fields: fld/residue.md
    - Ramification: fld/ramification.md
  - Univariate polynomials:
    - Introduction: upol/intro.md
    - Basic operations on  polynomial rings: upol/basics.md
    - Basic operations on polynomials: upol/elt-basics.md
    - Roots and factorization: upol/factoring.md
  - Multivariate polynomials:
    - Introduction: mpol/intro.md
    - Basic operations on  polynomial rings: mpol/basics.md
    - Basic operations on polynomials: mpol/elt-basics.md
